version: "3"

services:
  back:
    build:
      context: ./back/
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app/back
    command: >
      sh -c "python3 manage.py makemigrations &&
              python3 manage.py migrate &&
              python3 manage.py runserver 0.0.0.0:8000"

  front:
    build:
      context: ./front/
    ports:
      - "3000:8080"
    volumes:
      - ./front:/app/front
    depends_on:
      - back
