# Generated by Django 4.0.3 on 2022-03-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_article_create_at_alter_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('article', models.ManyToManyField(to='api.article')),
            ],
        ),
    ]
