# Generated by Django 4.0.3 on 2022-03-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_articlecommit_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecommit',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='commit',
            field=models.ManyToManyField(to='api.articlecommit'),
        ),
    ]
