# Generated by Django 4.0.3 on 2022-04-01 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='commit',
        ),
        migrations.AddField(
            model_name='articlecommit',
            name='article_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.article'),
            preserve_default=False,
        ),
    ]
