# Generated by Django 4.0.3 on 2022-04-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_article_commit_articlecommit_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(upload_to='media/%Y/%m/%d/'),
        ),
    ]
