# Generated by Django 4.0.3 on 2022-04-03 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_articlecommit_articlecomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecomment',
            old_name='article_id',
            new_name='article',
        ),
    ]
